### ISSUE TITLE
Could you also add NextJS i18n/Internationalization in this starter project? 

### ISSUE THREAD

**Issue by msundiitalk** [codegino/nextjs-typescript-tailwind-starter#134]
This ample is pretty cool to refer. If you could add **NextJS i18n**/Internationalization, **Sentry**,  **Apollo Client** as well will be great!

**Comment by codegino** [comment]
Hey. Apologies for the late response. Adding those things would be cool, but I prefer this boilerplate to be specific to Next, TypeScript, and Tailwind only.
